### PR TITLE
Updated to latest palette from the Design Manual

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updated the color palette to match the latest release from the Design Manual

## Testing

- run `npm link` in the project repo
- run `npm link cf-theme-cfpb` in a test project
- generate the styles (typically gulp build) and check for errors.

## Review

- @Scotchester 
- @anselmbradford

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
OK, now on this one, if this is going to be the canonical home for this file (and I still would like it to be), we should leave the search-and-replace instructions for people converting from the old palette intact. Or find a clear and obvious place to document that elsewhere.

**Comment by jimmynotjim** [comment]
I disagree on the canonical home. The CSV belongs to the DM and it seems that the process of updating anything related to that should live in the same project. 

I do agree on the helpfulness of the instructions, but making that happen in a script is uber complex. Maybe that should live outside this file, linked in the README? Whomever is adding this theme to an old project should be reading the instructions before getting started.

**Comment by Scotchester** [comment]
The home of the CSV and the home of the Less file could maybe two different considerations?

I think agree that it makes sense for the CSV to live in the Design Manual, but how will most projects (including the DM itself) be interacting with the palette and getting updates for it? Hopefully by updating their cf-theme-cfpb dependency.

In that regard, I think I agree that putting it in this project's README would make sense, yes.

**Comment by jimmynotjim** [comment]
Having the CSV and Less live in different repos seems overly complex when trying to link the source and the output in the script.

Let's play out what it'll take to make a change:

1. Update the CSV and save it to this project
2. Run the script to generate the Less file
3. Release the theme change
4. Save the new CSV in the DM repo
5. Update the theme in the DM repo
6. Regenerate everything
7. Release the DM change

Does that sound right?

**Comment by Scotchester** [comment]
That mostly sound right, but I'm not sure why we'd maintain the CSV and regenerate the Less in _two_ places.

Here's how I'd envision it:

1. Update the CSV and commit the changes in cf-theme-cfpb
1. Run the script in cf-theme-cfpb to generate a new `color-palette.less` file
1. Release a new version of cf-theme-cfpb
1. Update the version of the cf-theme-cfpb dependency in another project, e.g., design-manual
1. Use that project's typical build process to propagate the variables from cf-theme-cfpb's color-palette.less throughout the project's Less files
1. Release a new version of the project

How does that sound?

**Comment by jimmynotjim** [comment]
Discussed in person. Plan is to update the DM to use the theme with the CSV living within the theme and copied to the `_data` directory in the DM.

**Pull request closed without merging**
